### ISSUE TITLE
Unrecognized cop or department RSpecRails/HttpStatus

### ISSUE THREAD

**Issue by bestwebua** [rubocop/rubocop-rspec_rails#8]
Hello! Today I have faced with interesting issue:

```bash
Error: unrecognized cop or department RSpecRails/HttpStatus found in /home/circleci/vendor/bundle/ruby/3.3.0/gems/rubocop-rspec_rails-2.28.1/config/default.yml
Did you mean `RSpecRails/HaveHttpStatus`?
```

Current stack:
`ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin22]`
`'rubocop', '~> 1.62', '>= 1.62.1'`
`'rubocop-performance', '~> 1.20', '>= 1.20.2'`
`'rubocop-rspec', '~> 2.28'`

Here is failed step on CI:
https://app.circleci.com/pipelines/github/on-strum/ruby-on-strum-logs/79/workflows/112f2214-e921-4cc7-8fde-1ee8952a157e/jobs/627

Here is my current Rubocop configuration:
https://github.com/on-strum/ruby-on-strum-logs/blob/master/.circleci/linter_configs/.rubocop.yml

What am I doing wrong? Thanks!

**Comment by mjankowski** [comment]
Similar issue in other repo: https://github.com/rubocop/rubocop-rspec/issues/1846#issuecomment-2027510761

I'm curious if the release notes are correct and the names should be aliased ... or if that's wrong and we need to rename these with this version bump.

**Comment by pboling** [comment]
I am getting the same error

**Comment by ydah** [comment]
I realized it's a strange phenomenon.

When rubocop-rails and rubocop-rspec are present, the setting RSpec/Rails/HttpStatus causes an Ambiguous cop name error.

```
❯ rubocop -V
1.62.1 (using Parser 3.3.0.5, rubocop-ast 1.31.2, running on ruby 3.3.0) [arm64-darwin23]
  - rubocop-rails 2.24.1
  - rubocop-rspec 2.28.0
```

The following do not cause an error:
```yaml
# .rubocop.yml
require:
  - rubocop-rails

RSpec/Rails/HttpStatus:
  EnforcedStyle: numeric
```

```
❯ bundle exec rubocop
.rubocop.yml: RSpec/Rails/HttpStatus has the wrong namespace - replace it with Rails/HttpStatus
Inspecting 4 files
....

4 files inspected, no offenses detected
```

However, the following do cause an error:
```yaml
require:
  - rubocop-rails
  - rubocop-rspec

RSpec/Rails/HttpStatus:
  EnforcedStyle: numeric
```

```
❯ bundle exec rubocop
Error: Ambiguous cop name `RSpec/Rails/HttpStatus` used in /ydah/sandbox_capybara_with_rspec/.rubocop.yml needs department qualifier. Did you mean Rails/HttpStatus or RSpecRails/HttpStatus?
```

**Comment by bquorning** [comment]
What if you change the configuration key from `RSpec/Rails/HttpStatus:` to `RSpecRails/HttpStatus:`?

**Comment by ydah** [comment]
No errors or warnings are raised.

```
❯ bundle exec rubocop  
Inspecting 4 files
..C.
```

**Comment by bestwebua** [comment]
> What if you change the configuration key from `RSpec/Rails/HttpStatus:` to `RSpecRails/HttpStatus:`?

```yml
require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
```

I don't understand why this message is produces, I didn't use `rubocop-rails` at all. For me it's not an expected behavior.
